minima:
  nav_pages:
    - index.md
    - projects.md
    - about.md
    - Interests and Learning.md
  social_links:
    - { platform: github, user_id: prasad-888 }
    - { platform: linkedin, user_id: prasad-gavhane-373a55241 }


title: My Portfolio
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

