title: My Portfolio
remote_theme: jekyll/minima

header_pages:
  - index.md
  - projects.md
  - about.md
  - Interests and Learning.md

github_username: https://github.com/prasad-888
linkedin_username: prasad-gavhane-373a55241
